import { defineNuxtPlugin, useRuntimeConfig } from '#app';
// @ts-expect-error virtual file generated by Nuxt at build time
import { flyvaTransitions } from '#build/flyva-transitions.ts';

import { PageTransitionManager } from '../../shared/page-transition-manager';
import { supportsViewTransitions } from '../../shared/view-transition';
import { refReactiveFactory } from '../utils/refReactiveFactory';

export default defineNuxtPlugin(() => {
	const config = useRuntimeConfig().public;
	const vtEnabled = config.flyva?.viewTransition;

	if (import.meta.dev && vtEnabled && import.meta.client && !supportsViewTransitions()) {
		console.warn('[flyva] viewTransition is enabled but this browser does not support the View Transitions API');
	}

	const manager = new PageTransitionManager(flyvaTransitions ?? {}, refReactiveFactory, {
		viewTransition: vtEnabled,
		defaultTransitionKey: config.flyva?.defaultKey ?? 'defaultTransition',
	});

	return {
		provide: {
			flyvaManager: manager,
		},
	};
});

declare module '#app' {
	interface NuxtApp {
		$flyvaManager: PageTransitionManager;
	}
}

declare module 'vue' {
	interface ComponentCustomProperties {
		$flyvaManager: PageTransitionManager;
	}
}
