import { defineNuxtPlugin } from '#app';
// @ts-ignore virtual file generated by Nuxt at build time
import { flyvaTransitions } from '#build/flyva-transitions.ts';

import { PageTransitionManager } from '../../shared/page-tansition-manager';
import { refReactiveFactory } from '../utils/refReactiveFactory';

export default defineNuxtPlugin(() => {
	const manager = new PageTransitionManager(flyvaTransitions ?? {}, refReactiveFactory);

	return {
		provide: {
			flyvaManager: manager,
		},
	};
});

declare module '#app' {
	interface NuxtApp {
		$flyvaManager: PageTransitionManager;
	}
}

declare module 'vue' {
	interface ComponentCustomProperties {
		$flyvaManager: PageTransitionManager;
	}
}
